version: "3"
services:
  web:
    build: .
    ports:
      - "4000:4000"
      - "9229:9229"
    volumes:
      - .:/code
    working_dir: /code
    command: [ "npm", "run", "debug" ]
    environment:
      - NODE_ENV=development
